* SISU: [[https://github.com/vladmaraev/speechstate][SpeechState]] meets Information State Update (ISU)

The repo contains an ISU implementation based on: Kronlid, F., & Lager, T. (2007, May). [[https://archive.illc.uva.nl/semdial/proceedings/semdial2007_decalog_proceedings.pdf][Implementing the information-state update approach to dialogue management in a slightly extended SCXML]]. In Proceedings of the 11th International Workshop on the Semantics and Pragmatics of Dialogue (DECALOG) (pp. 99-106).

It also contains a partial implementation of the dialogue system IBiS1 (Larsson, Staffan (2002): [[https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=975e3dfccc0cf203565ea7fb370428743c1347a6][Issue-based Dialogue Management]]), including a small domain.

Prerequisites:
1. Install NodeJS (LTS version) and Yarn (v2 or higher).
2. Install all dependencies:
   #+begin_src 
     yarn
   #+end_src
3. In =src/azure.ts=, insert your Azure key where marked. This is required for running the system with speech (in browser frontend), but not for automated testing (in backend).

Run IBiS1:
1. Run backend in development mode:
   #+begin_src 
     yarn dev
   #+end_src
2. Open the link that was shown in your browser, e.g. http://localhost:5173/
3. Allow access to you microphone.
4. When you unblock the pop-up window, and reload the page you will see the state inspector; this can be useful during development.

Run automated tests:
#+begin_src
 yarn test
#+end_src
